### PR TITLE
About Page Updates

### PR DESCRIPTION
**Pull request by RBecker262**
I put together the About page talking about me, you and the program. You should like the fact that the Cardinals logo has found its way onto my website on this page. :)

6 file changes but 4 are just pictures. The other two are only HTML changes related to displaying the About page appropriately. No related code changes in this branch. Once the other branch is merged in I will have to make a small update to the views.py module to pass a new variable to the html pages to control the flash message area being displayed or not as I don't want it displayed on the About page.

### CODE REVIEW

**Review by alesage — COMMENTED** [review]
So just because you mention, why not roll that minor views.py change into this same pull request?  No objection to any changes.

Also note that as of today, the beginning of the all-star break, the Cubs and Cards have identical records.

**Comment by RBecker262** [comment]
I didn't because I had three different branches going to get all of these updates in. The views.py module had the significant work done in the other branch with the api routing and today's stats changes piling up. When I checked out this branch to make these HTML changes for About page, that branch did not have access to the views.py changes in the other branch. I could have copied them over through some trickery but wasn't sure the best way to handle the changes on top of changes already in progress.

**Comment by RBecker262** [comment]
I just pulled updated master down and am adding views.py changes into branch. Should be done in a little bit.

**Comment by RBecker262** [comment]
Closing and creating new after the pull I did a bit ago.

**Pull request closed without merging**
