### PR TITLE
adding all the cool web stuff to the project repository

### PR DESCRIPTION
**Pull request by RBecker262**
There is a lot here...all of the flask modules including the web server and api server, the html, the static pictures that go on the various pages. All web and nothing more. Tonight I will recreate my environment to make it lean, and I need to finish my blog!

The very first thing on the list below is a sample api module I'd like to keep but am no longer using. I found two ways to create api's using flask, one is just a prettier version of the other and uses more flask functions. I tried both ways and they both work. I talked with Ray on Thursday at the meeting to ask him what he knew of them and it was a good discussion. I decided to go with the pretty version but want to keep the other to have as a resource since it is the raw version to setting up an api, things the other flask functions somewhat hide.

### CODE REVIEW

**Comment by alesage** [comment]
Because this is so gigantic would you please do me a gigantic favor and brush up the README to include instructions on getting raw data?  A few words on running the demo server would be helpful too.  And then I'll issue my rubber stamp with a few snarky comments and/or yoda-like wisdom.

**Comment by RBecker262** [comment]
I will touch up the ReadMe doc with whatever is needed. Not sure what you mean by "getting raw data" though, can you please explain and I will update.

**Comment by alesage** [comment]
Just need a couple of command-line examples of using the backend scripts to
build your daily database.

**Comment by RBecker262** [comment]
Information requested has been added.

**Comment by RBecker262** [comment]
You will notice I made another commit just now. I created a new leaner environment using Python 3.4 as we discussed and ran some tests. I had been building/testing with the Flask environment created under the Mega Tutorial which used Python 3.5. Now that I dropped to 3.4 to run with Beanstalk properly, I found the Flask-WTF installed an older 3.4 compatible version than what I had been using under 3.5 and had to make an adjustment in the forms.py module.

**Review by alesage — APPROVED** [review]
Discussed and reviewed in person on 3.5, looks good, promising lots of snarky style comments at a later date.

**Pull request merged**
